version: 1
module_version: 1.4.4
test_defaults:
  before_init: ["terraform fmt -check"]
  runner_image: ghcr.io/mervinhemaraju/spacelift-runner-image:prod
tests:
  - name: Test with simple configurations
    terraform_version: 1.4.6
    project_root: "examples/minimal"
  - name: Test with environment variables
    terraform_version: 1.4.6
    project_root: "examples/environment_variables"
  - name: Test with context attachments
    terraform_version: 1.4.6
    project_root: "examples/environment_variables"
  - name: Test with gcp integration test
    terraform_version: 1.4.6
    project_root: "examples/gcp_integration"
  - name: Test with different project roots
    terraform_version: 1.4.6
    project_root: "examples/different_project_roots"
