version: 1
module_version: 1.0.0
test_defaults:
  before_init: ["terraform fmt -check"]
  runner_image: ghcr.io/mervinhemaraju/spacelift-runner-image:prod
tests:
  - name: Test with Simple Configurations
    terraform_version: 1.4.6
    project_root: "examples/minimal"
  - name: Test with Environment Variables
    terraform_version: 1.4.6
    project_root: "examples/environment_variables"
